### PR TITLE
v1.2.0: --max-file-size and verbatim/nocommment passes

### PR DESCRIPTION
**Pull request by Jelleas**
New:

1. ` --max-file-size` param that excludes any files bigger than that.
2. shows excluded files, and lists all of them in `--verbose`
3. optional verbatim & nocomments passes

### CODE REVIEW

**Comment by Jelleas** [comment]
One change, disabled the misspellings pass by default and enabled the verbatim pass by default. I've never found misspellings to be particularly useful myself, and I do think verbatim is a logical and useful default option.

**Comment by crossroads1112** [comment]
I think we should rethink the name of verbatim if we are going to make it a default. Currently it's so close to "exact" that i think people might be confused by the difference when they run compare50 for the first time.

**Comment by crossroads1112** [comment]
Or we could change the name of "exact". We'd need something that gets at the idea that it removes whitespace.

**Comment by crossroads1112** [comment]
What about "text", "code", and "structure"? If we aren't removing whitespace we are kinda sorta comparing the files as if they were text (kinda... We are still tokenizing). "code" kinda gets at the idea that we are only comparing stuff that actually gets executed (i.e. not whitespace) and then structure is clear.

**Comment by crossroads1112** [comment]
Also, I just pushed a small bugfix that showed up if you ran e.g. `compare50 someDirThatDoesntExist/*`. If the directory doesn't exist, the shell doesn't expand the pattern and just leaves it as is (i.e. it passes "someDirthatDoesn'tExist/*" as the only arg to compare50). That's fine, but then we try to do our own globbing internally and our globbing doesn't have the same behavior as the shell. Our globbing just returns an empty list so `args.submission` just ends up being empty which causes an error. I just made our internal globbing mimic the shell's behavior i.e. if we don't find any files/directories from globbing we just return the string itself.

**Comment by Jelleas** [comment]
Mmmm.... `code` and `text` seems a little off. We're always comparing code and we're not comparing text. We still pull everything through a lexer first.

Might be best if we move `exact` to mean an "exact match/comparison", where everything matches (including whitespace). Then we could use `code` for a `code match/comparison` where we compare just the code (excluding whitespace). That means we'll have `structure`, `code` and `exact` by default. Thoughts?

Relevant xkcd: https://xkcd.com/910/

**Comment by Jelleas** [comment]
Ugh, thinking about it, `code` does somewhat imply we'd be excluding comments. Perhaps `text` is best then?

`structure`, `text`, `exact`

**Comment by crossroads1112** [comment]
Yeah, I'm fine with this

**Pull request merged**
